export const routeLabels: Record<string, string> = {
    '/': 'Главная',
    account: 'Личный кабинет',
    plans: 'Тарифы',
    contacts: 'Контакты',
    decision: 'Решение',
    practice: 'Практика',
    experience: 'Опыт автора',
    runes: 'Спросить у рун',
    cards: 'Спросить у карт',
    sadness: 'Мне грустно',
    tarot: 'Таро',
    metaphoric: 'Метафорические карты',
    ['mind-games']: 'Игры разума',
    promo: 'Экспресс-карта',
    lenormand: 'Гадание Госпожи Ленорман',
    relaxation: 'Хочу расслабиться',
    iching: 'Таблица Гексаграмм',
    audios: 'Послание поддержки',
    affirmations: 'Аффирмация на день',
    toolkit: 'Полезные ресурсы',
};
